---
name: 'Execute CloudConformity scan on stack template'
description: Using reecetech's Hermitcrab tooling, this action staticly analyses Cloudformation templates.

branding:
  icon: 'zap'
  color: yellow

inputs:
  aws-region:
    description: 'AWS region for the Cloudformation stack'
    required: true
  cloudconformity-account-id:
    description: 'Cloud Conformity account ID for data payload'
    required: false
  cloudconformity-api-key:
    description: 'Cloud Conformity API key'
    required: true
  file-path:
    description: 'Path to CloudFormation template'
    required: true

runs:
  using: 'composite'
  steps:
    - name: "Checkout code 📥"
      uses: actions/checkout@v3
      with:
        repository: reecetech/cfn-scan-action
        path: cfn-scan

    - name: "Run scan script 🔎" 
      shell: bash
      run: ls -la && ./scan_cloudformation.sh
      env:
        AWS_REGION: ${{ inputs.aws-region }}
        CC_API_KEY: ${{ inputs.cloudconformity-api-key }}
        CC_ACCOUNT_ID: ${{ inputs.cloudconformity-account-id }}
        FILE_PATH: ${{ inputs.file-path }}
